### ISSUE TITLE
Installation test fails on one occation

### ISSUE THREAD

**Issue by rajaiyer** [metrumresearchgroup/Torsten#5] opened 2019-02-17 05:33 UTC
I was able to install torsten and it all went well. However when testing the installation there one test that fails (line 78 shows the error). Is there some configuration that could be changed to make this error free ?

Thanks in advance.
ri

[result_model.txt](https://github.com/metrumresearchgroup/Torsten/files/2872687/result_model.txt)

**Comment by yizhang-cae** [comment] 2019-02-17 21:16
I’ll try to reproduce the issue. Meanwhile could you provide information on the compiler and operation system? Thanks.
  
  
  
  
 -YZ  

  
  
  

  
  
>

**Comment by rajaiyer** [comment] 2019-02-18 05:22
I am trying to develop this within a docker container within an Ubuntu 18.04. I start with the latest  rocker/verse install clang and basically follow the instructions provided within the Tosten wiki. 

Thanks
ri

**Comment by yizhang-cae** [comment] 2019-02-18 22:41
Please rerun the patched master and let me know if the error is gone. You don't need to rebuild Torsten since only the `tests` folder has been updated. The exception you were running into is not caused by Torsten functions but how the tests were defined.

**Comment by rajaiyer** [comment] 2019-02-20 04:43
I did re-run it and that error seems is resolved. 

However, I came across another warning when "./test-torsten.sh --unit  " was executed. On line 221 in the attached result file you see the warning 
"WARNING: GRADIENT TESTS FOR GENERAL_ODE_BDF FAILS. SEE ISSUE 45". Seems like there is a problem with solution of a differential equation in one of the tests. 

Any thoughts about it?

Thanks
ri

[result_unit.txt](https://github.com/metrumresearchgroup/Torsten/files/2883047/result_unit.txt)

**Comment by yizhang-cae** [comment] 2019-02-20 15:38
It's leftover message from an old issue that will be patched in next release. Please ignore it for now. Thank you.

**Comment by rajaiyer** [comment] 2019-02-20 18:27
Thanks fora all the help. 
ri

**Comment by yizhang-cae** [comment] 2019-02-20 18:28
Sure. Please close the issue if you believe it's resolved. Thank you.

**Closed** 2019-02-21 06:17 UTC
